### ISSUE TITLE
help info in rodeo_main.py

### ISSUE THREAD

**Issue by fallinwind** [the-mitchell-lab/rodeo2#31]
parser.add_argument('-out', '--output_dir', type=str,
                        help='Name of output folder')
    parser.add_argument('-c', '--conf_file', nargs='*', default=[],
                        help='Maximum size of potential ORF')
    parser.add_argument('-hmm', '--custom_hmm', nargs='*', default=[],
                        help='Maximum size of potential ORF')
    parser.add_argument('-j', '--num_cores', type=int, default = 1,
                        help="Number of cores to use.")
    parser.add_argument('-max', '--precursor_max', type=int,
                        help='Maximum size of potential ORF') #better word for potential?
    parser.add_argument('-min', '--precursor_min', type=int,
                        help='Minimum size of potential ORF')

wrong argument help info "Maximum size of potential ORF"

**Comment by thedamlab** [comment]
Fixed. Thank you for you pointing this out.
