### ISSUE TITLE
Unable to open local genbank files

### ISSUE THREAD

**Issue by AaronAOliver** [the-mitchell-lab/rodeo2#6]
I've been unable to input my own local .gbk files into rodeo2, so as a test I downloaded the AB593691.gbk file from Genbank that is described in the usage instructions. I'm getting the following error messages, which also appear when I try to input other local Genbank files:

`$python rodeo_main.py AB593691.gbk`

`2020-07-19 22:50:26,438 - rodeo_main - WARNING - Overwriting AB593691_rodeo_out folder.`
`Process Process-3:`
`Traceback (most recent call last):`
  `File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap`
    `self.run()`
  `File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run`
    `self._target(*self._args, **self._kwargs)`
  `File "/home/aaron/rodeo2-master/record_processing.py", line 138, in fill_request_queue`
    `gb_handles = [open(query.split('\t')[1])]`
`IndexError: list index out of range`

I am able to directly call `python rodeo_main.py BAL72546` and get the correct output, so direct Genbank accession IDs do work. However, the data I am interested in running through rodeo2 is not yet on Genbank so I need rodeo2 to work on my local files.

**Comment by TaehyungKwon** [comment]
I think you need to provide a list of genbank IDs, because anyway it won't work with the content of GenBank file. in my experience. Let me know if I am wrong!

**Comment by serina-robinson** [comment]
Hello, I am curious about the same thing and the genbank file example for AB593691.gbk is giving me the same error. Any advice as to workarounds or how to run RODEO for non-NCBI sequences (see also the other issue: https://github.com/the-mitchell-lab/rodeo2/issues/7#issue-697153006) would be helpful! I really appreciate your tool!

**Comment by srdommaraju** [comment]
Hi all,

We are aware of these issues. The version of RODEO we have made publicly available is deliberately restricted to working with genomes that are publicly available in NCBI databases. If you are interested in using RODEO for private/proprietary genomes, please contact Prof. Mitchell directly.
