### ISSUE TITLE
Is there any roadmap for NCBI-independent rodeo run?

### ISSUE THREAD

**Issue by TaehyungKwon** [the-mitchell-lab/rodeo2#7]
Dear All,

Thank you for the great software. One thing I wonder is that is there any future goal of Rodeo to be independent from NCBI database? I would like to utilize my own genbank-format protein sequences that are yet or not registered in NCBI.

Thanks!

**Comment by srdommaraju** [comment]
Hello,

I'm copying the response from the the previous issue for documentation purposes. 

We are aware of these issues. The version of RODEO we have made publicly available is deliberately restricted to working with genomes that are publicly available in NCBI databases. If you are interested in using RODEO for private/proprietary genomes, please contact Prof. Mitchell directly.

**Comment by TaehyungKwon** [comment]
Thanks!
